Added popup UI and UI functionality
AJKaz/Goofy-Goobers pull request #12
Opened 2023-11-08 17:46 UTC by PrvCaboose

Tower and Spell buttons work and activate properly, so far only the first spell does something, but it doesn't affect the enemies yet, just collides with them. All Main UI buttons have a hover mechanic where an info panel shows up, and towers have a info panel show up on click, and disappear when they click off. Tower info panels remain within the bounds of the screen.

2023-11-08 23:08 UTC, AJKaz approved these changes
nice work, consider changing those few things tho

2023-11-08 23:08 UTC, AJKaz commented on Defend The Divine/Assets/Scripts/Spells/FreezeSpell.cs
> +    public void SetStats(float damage, float speed)
don't need damage

2023-11-08 23:08 UTC, AJKaz commented on Defend The Divine/Assets/Scripts/Towers/TowerPlacement.cs
> +                    towerType2Prefab = null;
why do you set the prefab to null?

2023-11-09 00:24 UTC, ArgentumRhodon requested changes
I would address AJ's concerns before merging. I didn't find anything that he didn't already comment on.

2023-11-09 23:34 UTC, merged